apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "kawalepankaj",
          "password": "<DOCKER_PASSWORD_OR_TOKEN>",
          "email": "<YOUR_EMAIL>",
          "auth": "<BASE64_ENCODED_USERNAME_PASSWORD>"
        }
      }
    }
